Update cs2-all-build.yml

diff --git a/.github/workflows/cs2-all-build.yml b/.github/workflows/cs2-all-build.yml
--- a/.github/workflows/cs2-all-build.yml
+++ b/.github/workflows/cs2-all-build.yml
@@ -7,14 +7,21 @@ on:
         description: 'Release date (yyyymmdd)'
         required: true
 
+env:
+  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
+  QT_VERSION: 6.12.0
+
 jobs:
-  mac_build:
-    runs-on: macos-14
+  setup:
+    runs-on: ubuntu-latest
+    # ジョブ単位で定義する場合はここに env: QT_VERSION: 6.12.0 でも可
     outputs:
+      qt_version: ${{ env.QT_VERSION }}
       tag: ${{ steps.setvars.outputs.tag }}
       title: ${{ steps.setvars.outputs.title }}
-
     steps:
+      - run: echo "QT_VERSION=${{ env.QT_VERSION }}"  # ジョブには最低1ステップ必要
+
       - name: Set release variables
         id: setvars
         run: |
@@ -22,14 +29,25 @@ jobs:
           title="${tag:0:4}/${tag:4:2}/${tag:6:2}版リリース"
           echo "tag=$tag" >> $GITHUB_OUTPUT
           echo "title=$title" >> $GITHUB_OUTPUT
+          
+      - name: Format release title
+        id: format_date
+        run: |
+          yyyy=${{ github.event.inputs.yyyymmdd }} 
+          echo "title=${yyyy:0:4}/${yyyy:4:2}/${yyyy:6:2}版リリース" >> "$GITHUB_OUTPUT"
+          
+  mac_build:
+    needs: setup
+    runs-on: macos-26
 
+    steps:
       - name: Checkout
         uses: actions/checkout@v6
 
       - name: Install Qt
         uses: jurplel/install-qt-action@v4
         with:
-          version: 6.11.*
+          version: '${{ needs.setup.outputs.qt_version }}'
           extra: '--external 7z'
 
       - name: Configure CMake
@@ -42,7 +60,7 @@ jobs:
 
       - name: Prepare CaptureStream2 executable
         run: |
-          wget -qO FFmpeg.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/8.0/ffmpeg-macos-universal.tar.gz || { echo "Failed to download FFmpeg"; exit 1; }
+          wget -qO FFmpeg.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-macos-universal.tar.gz || { echo "Failed to download FFmpeg"; exit 1; }
           tar -xzvf FFmpeg.tar.gz ffmpeg
           cp ffmpeg ./build/CaptureStream2.app/Contents/MacOS/ 
           cp ./icon.icns ./build/CaptureStream2.app/Contents/Resources/
@@ -53,6 +71,7 @@ jobs:
           mkdir -p build/tmp/MacCaptureStream2
           mv build/CaptureStream2.app build/tmp/MacCaptureStream2/
           cp -r ./qss_files/License build/tmp/MacCaptureStream2/
+          ln -s /Applications build/tmp/MacCaptureStream2/Applications
           
       - name: Create DMG file
         run: |
@@ -60,8 +79,8 @@ jobs:
           hdiutil create -volname MacCaptureStream2 \
                       -srcfolder tmp \
                       -ov -format UDZO \
-                      "CaptureStream2-MacOS-${{ github.event.inputs.yyyymmdd }}.dmg"
-
+                      "CaptureStream2-MacOS-Universal-${{ github.event.inputs.yyyymmdd }}.dmg"
+                      
 #      - name: Format release title
 #        id: format_date
 #        run: |
@@ -71,8 +90,9 @@ jobs:
       - name: Upload DMG to GitHub Release
         uses: softprops/action-gh-release@v2.2.2
         with:
-          files: build/CaptureStream2-MacOS-${{ github.event.inputs.yyyymmdd }}.dmg
-          tag_name: ${{ github.event.inputs.yyyymmdd }}
+          files: build/CaptureStream2-MacOS-Universal-${{ github.event.inputs.yyyymmdd }}.dmg
+          tag_name: ${{ needs.setup.outputs.tag }}
+          name: ${{ needs.setup.outputs.title }}
 #          name: ${{ steps.format_date.outputs.title }}
 #          body: "Qt 6.9 build test"
         env:
@@ -80,9 +100,9 @@ jobs:
 
   win_build:
     runs-on: ubuntu-latest
-    needs: mac_build
+    needs: setup
     container:
-      image: ghcr.io/csreviser/qt6-mxe-static:6.11.0
+      image: ghcr.io/csreviser/qt6-mxe-static:${{ needs.setup.outputs.qt_version }}
 
     steps:
       - name: Checkout this repo
@@ -116,7 +136,9 @@ jobs:
           mv build/CaptureStream2.exe build/WinCaptureStream2/
           cp ./qss_files/stylesheet-win.qss build/WinCaptureStream2/
           cp -r ./qss_files/License build/WinCaptureStream2/
-          cp /opt/mxe/usr/x86_64-w64-mingw32.static/bin/ffmpeg.exe build/WinCaptureStream2/
+          wget -qO ffmpeg.zip https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-9.0.2-windows-x64-static.zip
+          7z e ffmpeg.zip ffmpeg.exe -o./build/WinCaptureStream2/
+ #         cp /opt/mxe/usr/x86_64-w64-mingw32.static/bin/ffmpeg.exe build/WinCaptureStream2/
 
       - name: Install GitHub CLI
         run: |
@@ -132,22 +154,24 @@ jobs:
       - name: Create ZIP file
         run: |
           cd build
-          zip -r "CaptureStream2-Windows-x64-${{ github.event.inputs.yyyymmdd }}.zip" WinCaptureStream2
+          zip -r "CaptureStream2-Windows-${{ github.event.inputs.yyyymmdd }}.zip" WinCaptureStream2
 
       - name: Upload Windows binary to existing release
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           cd build
-          gh release upload "${{ needs.mac_build.outputs.tag }}" \
-            "CaptureStream2-Windows-x64-${{ github.event.inputs.yyyymmdd }}.zip" \
+          gh release upload "${{ needs.setup.outputs.tag }}" \
+            "CaptureStream2-Windows-${{ github.event.inputs.yyyymmdd }}.zip" \
             --clobber
+
 
   win32_build:
     runs-on: ubuntu-latest
-    needs: mac_build
+    needs: setup
     container:
-      image: ghcr.io/csreviser/qt6-mxe-x86-static:6.11.0
+       image: ghcr.io/csreviser/qt6-mxe-static-path:${{ needs.setup.outputs.qt_version }}-32
+#      image: ghcr.io/csreviser/qt6-mxe-x86-static:'${{ needs.setup.outputs.qt_version }}
 
     steps:
       - name: Checkout this repo
@@ -192,7 +216,9 @@ jobs:
           mv build/CaptureStream2.exe build/WinCaptureStream2/
           cp ./qss_files/stylesheet-win.qss build/WinCaptureStream2/
           cp -r ./qss_files/License build/WinCaptureStream2/
-          cp /opt/mxe/usr/i686-w64-mingw32.static/bin/ffmpeg.exe build/WinCaptureStream2/
+          wget -qO ffmpeg.zip https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-9.0.2-windows-x86-static.zip
+          7z e ffmpeg.zip ffmpeg.exe -o./build/WinCaptureStream2/
+#          cp /opt/mxe/usr/i686-w64-mingw32.static/bin/ffmpeg.exe build/WinCaptureStream2/
           
       - name: Create ZIP file
         run: |
@@ -204,16 +230,16 @@ jobs:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           cd build
-          gh release upload "${{ needs.mac_build.outputs.tag }}" \
+          gh release upload "${{ needs.setup.outputs.tag }}" \
             "CaptureStream2-Windows-x86-${{ github.event.inputs.yyyymmdd }}.zip" \
             --clobber
 
   appimage:
-    name: Build in Docker
+    name: Build in Docker-arm
     runs-on: ubuntu-22.04-arm
-    needs: mac_build
+    needs: setup
     container:
-      image: ghcr.io/csreviser/qt6-static-arm:latest
+      image: ghcr.io/csreviser/qt6-static-arm:${{ needs.setup.outputs.qt_version }}-ubuntu22.04
       options: --privileged
 
     steps:
@@ -282,8 +308,8 @@ jobs:
           mkdir -p LinCaptureStream2
           cp ../qss_files/stylesheet-ubu.qss ./LinCaptureStream2
           cp -r ../qss_files/License ./LinCaptureStream2
-          wget -qO ffmpeg-static-ubuntu-arm.zip https://github.com/CSReviser/ffmpeg-build/releases/download/7.1.1/ffmpeg-static-ubuntu-arm.zip
-          7z e ffmpeg-static-ubuntu-arm.zip ffmpeg -o./LinCaptureStream2
+          wget -qO ffmpeg-static-ubuntu-arm.zip https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-arm-static.zip
+          7z x ffmpeg-static-ubuntu-arm.zip -o./LinCaptureStream2/ffmpeg-ubu
           chmod -R 755 ./LinCaptureStream2
           
       - name: Build AppImage without FUSE
@@ -323,9 +349,9 @@ jobs:
   build-app:
     name: Build in Docker
     runs-on: ubuntu-22.04
-    needs: mac_build
+    needs: setup
     container:
-      image: ghcr.io/csreviser/qt6-static:6.11.0-ubuntu22.04
+      image: ghcr.io/csreviser/qt6-static:${{ needs.setup.outputs.qt_version }}-ubuntu22.04
       options: --privileged
     steps:
       - name: Checkout source
@@ -398,8 +424,8 @@ jobs:
          cp ../CaptureStream2-x86_64.AppImage ./LinCaptureStream2/CaptureStream2
          cp ../qss_files/stylesheet-ubu.qss ./LinCaptureStream2
          cp -r ../qss_files/License ./LinCaptureStream2
-         wget -qO ffmpeg-static-ubuntu.zip https://github.com/CSReviser/ffmpeg-build/releases/download/7.1.1/ffmpeg-static-ubuntu.zip
-         7z e ffmpeg-static-ubuntu.zip ffmpeg -o./LinCaptureStream2
+         wget -qO ffmpeg-static-ubuntu.zip https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-static.zip
+         7z x ffmpeg-static-ubuntu.zip -o./LinCaptureStream2/ffmpeg-ubu
          chmod -R 755 ./LinCaptureStream2
 #          ./linuxdeployqt.AppImage AppDir/CaptureStream2.desktop \
 #           -appimage -bundle-non-qt-libs 
@@ -411,15 +437,15 @@ jobs:
         uses: softprops/action-gh-release@v2
         with:
           files: CaptureStream2/build/CaptureStream2-AppImage-x64-${{ github.event.inputs.yyyymmdd }}.zip
-          tag_name: ${{ github.event.inputs.yyyymmdd }}
+          tag_name: ${{ needs.setup.outputs.tag }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             
   ubuntu_build:
     runs-on: ubuntu-latest
-    needs: mac_build
+    needs: setup
     container:
-      image: ghcr.io/csreviser/qt6-static:6.11.0-ubuntu22.04
+      image: ghcr.io/csreviser/qt6-static:${{ needs.setup.outputs.qt_version }}-ubuntu22.04
 # ghcr.io/csreviser/qt6-static:6.9.0-ubuntu22.04
 # ghcr.io/csreviser/qt6-ubuntu-static:latest
 
@@ -450,7 +476,7 @@ jobs:
           mv CaptureStream2 ./LinCaptureStream2/
           cp ../qss_files/stylesheet-ubu.qss ./LinCaptureStream2
           cp -r ../qss_files/License ./LinCaptureStream2
-          wget -qO ffmpeg-static-ubuntu.zip https://github.com/CSReviser/ffmpeg-build/releases/download/7.1.1/ffmpeg-static-ubuntu.zip
+          wget -qO ffmpeg-static-ubuntu.zip https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-static-ubuntu.zip
           7z e ffmpeg-static-ubuntu.zip ffmpeg -o./LinCaptureStream2
           chmod -R 755 ./LinCaptureStream2
 
@@ -467,68 +493,9 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  mac_qt5_build:
-    runs-on: macos-15
-    needs: mac_build
-
-    steps:
-      - name: Set release variables
-        id: setvars
-        run: |
-          tag=${{ github.event.inputs.yyyymmdd }}
-          title="${tag:0:4}/${tag:4:2}/${tag:6:2}版リリース"
-          echo "tag=$tag" >> $GITHUB_OUTPUT
-          echo "title=$title" >> $GITHUB_OUTPUT
-
-      - name: Checkout
-        uses: actions/checkout@v6
-
-      - name: Mark repo as safe
-        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
-
-      - name: Update GitHub CLI
-        run: |
-          brew install gh || brew upgrade gh
-
-      - name: Install Qt
-        uses: jurplel/install-qt-action@v4
-        with:
-          version: 6.2.*
-          extra: '--external 7z'
-
-      - name: qmake
-        run: |
-          qmake -makefile CaptureStream2.pro QMAKE_APPLE_DEVICE_ARCHS="x86_64"
-          make
-          wget -qO FFmpeg.7z https://evermeet.cx/ffmpeg/ffmpeg-7.1.1.7z
-          7z e FFmpeg.7z ffmpeg -o./CaptureStream2.app/Contents/MacOS/
-          chmod -R 755 ./CaptureStream2.app
-          mkdir -p ./build/tmp/MacCaptureStream2
-          cp ./icon.icns ./CaptureStream2.app/Contents/Resources/
-          cp ./qss_files/stylesheet-mac.qss ./CaptureStream2.app/Contents/MacOS/
-          mv ./CaptureStream2.app ./build/tmp/MacCaptureStream2/
-          cp -r ./qss_files/License ./build/tmp/MacCaptureStream2/
-          
-      - name: Create DMG file
-        run: |
-          cd build
-          hdiutil create -volname MacCaptureStream2 \
-                      -srcfolder tmp \
-                      -ov -format UDZO \
-                      "CaptureStream2-MacOS-qt6-2-${{ github.event.inputs.yyyymmdd }}.dmg"
-
-
-      - name: Upload DMG to GitHub Release
-        uses: softprops/action-gh-release@v2.2.2
-        with:
-          files: build/CaptureStream2-MacOS-qt6-2-${{ github.event.inputs.yyyymmdd }}.dmg
-          tag_name: ${{ needs.mac_build.outputs.tag }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
   mac_universal_build:
     runs-on: macos-15
-    needs: mac_build
+    needs: setup
 
     steps:
       - name: Set release variables
@@ -558,7 +525,7 @@ jobs:
 
       - name: Prepare CaptureStream2 executable
         run: |
-          wget -qO FFmpeg.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/8.0/ffmpeg-macos-universal.tar.gz || { echo "Failed to download FFmpeg"; exit 1; }
+          wget -qO FFmpeg.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-macos-universal.tar.gz || { echo "Failed to download FFmpeg"; exit 1; }
           tar -xzvf FFmpeg.tar.gz ffmpeg
           cp ffmpeg ./build/CaptureStream2.app/Contents/MacOS/ 
           cp ./icon.icns ./build/CaptureStream2.app/Contents/Resources/
@@ -582,6 +549,70 @@ jobs:
         uses: softprops/action-gh-release@v2.2.2
         with:
           files: build/CaptureStream2-MacOS-qt6-5-${{ github.event.inputs.yyyymmdd }}.dmg
-          tag_name: ${{ needs.mac_build.outputs.tag }}
+          tag_name: ${{ needs.setup.outputs.tag }}
+          name: ${{ needs.setup.outputs.title }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+
+
+  mac_apple_build:
+    runs-on: macos-26
+    needs: setup
+
+    steps:
+      - name: Set release variables
+        id: setvars
+        run: |
+          tag=${{ github.event.inputs.yyyymmdd }}
+          title="${tag:0:4}/${tag:4:2}/${tag:6:2}版リリース"
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Install Qt
+        uses: jurplel/install-qt-action@v4
+        with:
+          version: '${{ needs.setup.outputs.qt_version }}'
+          extra: '--external 7z'
+ #         modules: 'qtcharts'
+ 
+      - name: Clone CaptureStream2
+        run: |
+          git clone https://github.com/CSReviser/CaptureStream2.git
+          cd CaptureStream2
+          git submodule update --init --recursive
+      - name: Configure CMake
+        run: |
+          mkdir build
+          cmake -S CaptureStream2 -B build -DCMAKE_OSX_ARCHITECTURES="arm64"
+      - name: Build with Make
+        run: cmake --build build --parallel
+
+      - name: Prepare CaptureStream2 executable
+        run: |
+          wget -qO FFmpeg.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-macos-arm64.tar.gz || { echo "Failed to download FFmpeg"; exit 1; }
+          tar -xzvf FFmpeg.tar.gz ffmpeg
+          cp ffmpeg ./build/CaptureStream2.app/Contents/MacOS/ 
+          cp CaptureStream2/icon.icns ./build/CaptureStream2.app/Contents/Resources/
+          cp CaptureStream2/qss_files/stylesheet-mac.qss ./build/CaptureStream2.app/Contents/MacOS/
+      - name: Create MacCaptureStream2 directory
+        run: |
+          mkdir -p build/tmp/MacCaptureStream2
+          mv build/CaptureStream2.app build/tmp/MacCaptureStream2/
+          cp -r CaptureStream2/qss_files/License build/tmp/MacCaptureStream2/
+          ln -s /Applications build/tmp/MacCaptureStream2/Applications
+      - name: Create DMG file
+        run: |
+          cd build
+          hdiutil create -volname MacCaptureStream2 \
+                      -srcfolder tmp \
+                      -ov -format UDZO \
+                      "CaptureStream2-MacOS-AppleSilicon-${{ github.event.inputs.yyyymmdd }}.dmg"
+      - name: Upload DMG to GitHub Release
+        uses: softprops/action-gh-release@v2
+        with:
+          files: build/CaptureStream2-MacOS-AppleSilicon-${{ github.event.inputs.yyyymmdd }}.dmg
+          tag_name: ${{ needs.setup.outputs.tag }}
+          name: ${{ needs.setup.outputs.title }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
